In [1]:
# what is this line all about?!? Answer in lecture 4
%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
from numpy import *

In [3]:
v=array([1,2,3,4])
v

array([1, 2, 3, 4])

In [4]:
# a matrix: the argument to the array function is a nested Python list
M = array([[1, 2], [3, 4]])

M

array([[1, 2],
       [3, 4]])

In [5]:
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

In [7]:
v.shape, M.shape

((4,), (2, 2))

In [8]:
M.dtype

dtype('int32')

In [9]:
x=arange(100,110,2)

x

array([100, 102, 104, 106, 108])

In [11]:
a = array([[1, 2, 3], [4, 5, 6]])

In [12]:
a.shape

(2, 3)

In [13]:
# using linspace, both end points ARE included
linspace(0, 10, 25)

array([  0.        ,   0.41666667,   0.83333333,   1.25      ,
         1.66666667,   2.08333333,   2.5       ,   2.91666667,
         3.33333333,   3.75      ,   4.16666667,   4.58333333,
         5.        ,   5.41666667,   5.83333333,   6.25      ,
         6.66666667,   7.08333333,   7.5       ,   7.91666667,
         8.33333333,   8.75      ,   9.16666667,   9.58333333,  10.        ])

In [14]:
help(linspace)

Help on function linspace in module numpy.core.function_base:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    Parameters
    ----------
    start : scalar
        The starting value of the sequence.
    stop : scalar
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    retstep : bo

In [15]:
linspace(1,5,5)

array([ 1.,  2.,  3.,  4.,  5.])

In [16]:
help(logspace)

Help on function logspace in module numpy.core.function_base:

logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
    Return numbers spaced evenly on a log scale.
    
    In linear space, the sequence starts at ``base ** start``
    (`base` to the power of `start`) and ends with ``base ** stop``
    (see `endpoint` below).
    
    Parameters
    ----------
    start : float
        ``base ** start`` is the starting value of the sequence.
    stop : float
        ``base ** stop`` is the final value of the sequence, unless `endpoint`
        is False.  In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length `num`) are returned.
    num : integer, optional
        Number of samples to generate.  Default is 50.
    endpoint : boolean, optional
        If true, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    base : float, optional
        The base of 

In [17]:
logspace(1,5,5,base=10)

array([  1.00000000e+01,   1.00000000e+02,   1.00000000e+03,
         1.00000000e+04,   1.00000000e+05])

In [18]:
help(mgrid)

Help on nd_grid in module numpy.lib.index_tricks object:

class nd_grid(builtins.object)
 |  Construct a multi-dimensional "meshgrid".
 |  
 |  ``grid = nd_grid()`` creates an instance which will return a mesh-grid
 |  when indexed.  The dimension and number of the output arrays are equal
 |  to the number of indexing dimensions.  If the step length is not a
 |  complex number, then the stop is not inclusive.
 |  
 |  However, if the step length is a **complex number** (e.g. 5j), then the
 |  integer part of its magnitude is interpreted as specifying the
 |  number of points to create between the start and stop values, where
 |  the stop value **is inclusive**.
 |  
 |  If instantiated with an argument of ``sparse=True``, the mesh-grid is
 |  open (or not fleshed out) so that only one-dimension of each returned
 |  argument is greater than 1.
 |  
 |  Parameters
 |  ----------
 |  sparse : bool, optional
 |      Whether the grid is sparse or not. Default is False.
 |  
 |  Notes
 |  --

In [20]:
help(genfromtxt)

Help on function genfromtxt in module numpy.lib.npyio:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=None, replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None)
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is `.gz` or `.bz2`, the file is first decompressed. Note
        that generators must return byte strings in Python 3k.  The strings
        in a list or 

In [22]:
data_dir='../DataFiles/'
cities = genfromtxt(data_dir+'Cities.csv', delimiter=',')
cities

array([[   nan,    nan,    nan],
       [ 4001.,    nan,    nan],
       [ 4002.,    nan,    nan],
       ..., 
       [ 4402.,    nan,    nan],
       [ 4403.,    nan,    nan],
       [ 4404.,    nan,    nan]])

In [24]:
cities.shape


(405, 3)

In [26]:
M=random.rand(3,3)

In [27]:
M

array([[ 0.15931087,  0.13242281,  0.6664273 ],
       [ 0.93802251,  0.81869459,  0.65909548],
       [ 0.88824988,  0.94545501,  0.86419682]])

In [28]:
savetxt('random_mat.txt', M)

In [31]:
!cat random_mat.txt

1.593108728668951590e-01 1.324228130768059231e-01 6.664273037415359147e-01
9.380225107128248307e-01 8.186945911653903396e-01 6.590954780926706613e-01
8.882498753516919754e-01 9.454550079221605285e-01 8.641968209767540987e-01


In [30]:
!cat random_mat.txt

1.593108728668951590e-01 1.324228130768059231e-01 6.664273037415359147e-01
9.380225107128248307e-01 8.186945911653903396e-01 6.590954780926706613e-01
8.882498753516919754e-01 9.454550079221605285e-01 8.641968209767540987e-01


In [32]:
M[0]

array([ 0.15931087,  0.13242281,  0.6664273 ])

In [34]:
M[:,0]

array([ 0.15931087,  0.93802251,  0.88824988])

In [35]:
M[1,:]=1

In [36]:
M

array([[ 0.15931087,  0.13242281,  0.6664273 ],
       [ 1.        ,  1.        ,  1.        ],
       [ 0.88824988,  0.94545501,  0.86419682]])

In [37]:
A=array([1,2,3,4,5])

In [38]:
A

array([1, 2, 3, 4, 5])

In [40]:
A[::2] *= -1

In [41]:
A

array([-1,  2, -3,  4, -5])

In [42]:
A[3:]

array([ 4, -5])

In [43]:
A

array([-1,  2, -3,  4, -5])

In [44]:
M

array([[ 0.15931087,  0.13242281,  0.6664273 ],
       [ 1.        ,  1.        ,  1.        ],
       [ 0.88824988,  0.94545501,  0.86419682]])

In [45]:
M[:1,:1]

array([[ 0.15931087]])

In [46]:
M[:2,:1]

array([[ 0.15931087],
       [ 1.        ]])

In [47]:
B=array([n for n in range(5)])

In [49]:
mask=array([True,False,True,False,False])

In [50]:
B[mask]

array([0, 2])

In [51]:
x=arange(0,10,0.5)

In [52]:
mask=(5<x)*(x<7.5)

In [53]:
x[mask]

array([ 5.5,  6. ,  6.5,  7. ])

In [57]:
A=array([[n + m*10 for n in arange(5)] for m in arange(5)])
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [58]:
A*A

array([[   0,    1,    4,    9,   16],
       [ 100,  121,  144,  169,  196],
       [ 400,  441,  484,  529,  576],
       [ 900,  961, 1024, 1089, 1156],
       [1600, 1681, 1764, 1849, 1936]])

In [59]:
v1 = arange(0, 5)

In [60]:
v1

array([0, 1, 2, 3, 4])

In [61]:
v1.shape

(5,)

In [62]:
v1[:0]

array([], dtype=int32)

In [63]:
v2=array([[n] for n in range(5)])
v2.shape

(5, 1)

In [64]:
A*v1

array([[  0,   1,   4,   9,  16],
       [  0,  11,  24,  39,  56],
       [  0,  21,  44,  69,  96],
       [  0,  31,  64,  99, 136],
       [  0,  41,  84, 129, 176]])

In [65]:
A*v2

array([[  0,   0,   0,   0,   0],
       [ 10,  11,  12,  13,  14],
       [ 40,  42,  44,  46,  48],
       [ 90,  93,  96,  99, 102],
       [160, 164, 168, 172, 176]])

In [69]:
M=matrix(A)
V=matrix(v1).T

In [70]:
V

matrix([[0],
        [1],
        [2],
        [3],
        [4]])

In [71]:
M

matrix([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34],
        [40, 41, 42, 43, 44]])

In [72]:
a=array([[1,2],[3,4]])
b=array([[5,6]])
a.shape,b.shape

((2, 2), (1, 2))

In [73]:
concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [75]:
concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])